import ContactForm from '@/components/contactForm';
import Footer from '@/components/footer';
import Instructions from '@/components/instructions';
import NavBar from '@/components/navbar';
import Head from 'next/head';

export default function Contact() {
  return (
    <>
      <Head>
        <title>Contato</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <NavBar />
      <ContactForm />
      <Instructions />
      <Footer />
    </>
  );
}
