import Head from 'next/head';
import NavBar from '@/components/navbar';
import ActivePrizes from '@/components/activePrizes';
import Winners from '@/components/winners';
import Instructions from '@/components/instructions';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <NavBar />
      <ActivePrizes />
      <Winners />
      <Instructions />
    </>
  );
}
